In [1]:
# DAY 2: Data Cleaning + SQL Database Design
# Task 1: Clean NAV History Data

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_nav = pd.read_csv("../data/raw/02_nav_history.csv")
df_nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
df_nav.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [5]:
df_nav["date"] = pd.to_datetime(df_nav["date"])
df_nav.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[us]
 2   nav        46000 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 1.1 MB

In [6]:
df_nav = df_nav.sort_values(["amfi_code", "date"])
df_nav.head(10)

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639
5755     100016 2022-01-10  510.7136
5756     100016 2022-01-11  513.5542
5757     100016 2022-01-12  512.3195
5758     100016 2022-01-13  510.2445
5759     100016 2022-01-14  514.3636

In [7]:
df_nav["nav"].isnull().sum()

np.int64(0)

In [8]:
df_nav.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [9]:
df_nav.duplicated().sum()

np.int64(0)

In [10]:
(df_nav["nav"] <= 0).sum()

np.int64(0)

In [11]:
df_nav[df_nav["nav"] <= 0]

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [12]:
df_nav.to_csv("../data/processed/clean_nav.csv", index=False)

In [13]:
clean_nav = pd.read_csv("../data/processed/clean_nav.csv")
clean_nav.shape

(46000, 3)

In [14]:
# Task 2: Clean INVESTOR TRANSACTIONS Data

In [15]:
df_trans = pd.read_csv("../data/raw/08_investor_transactions.csv")
df_trans.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [16]:
df_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [17]:
df_trans.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [18]:
df_trans.duplicated().sum()

np.int64(0)

In [19]:
df_trans["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [20]:
df_trans["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [21]:
(df_trans["amount_inr"] <= 0).sum()

np.int64(0)

In [22]:
df_trans["amount_inr"].describe()

count     32778.000000
mean     107437.318628
std      150415.905084
min         400.000000
25%        3153.000000
50%       17782.500000
75%      189324.250000
max      597498.000000
Name: amount_inr, dtype: float64

In [23]:
df_trans["transaction_date"].head(10)

0    2024-01-01
1    2024-01-01
2    2024-01-01
3    2024-01-01
4    2024-01-01
5    2024-01-01
6    2024-01-01
7    2024-01-01
8    2024-01-01
9    2024-01-01
Name: transaction_date, dtype: str

In [24]:
df_trans["transaction_date"] = pd.to_datetime(df_trans["transaction_date"])

In [25]:
df_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  datetime64[us]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(9)
memory usage: 3.3 MB

In [26]:
df_trans["transaction_date"].head()

0   2024-01-01
1   2024-01-01
2   2024-01-01
3   2024-01-01
4   2024-01-01
Name: transaction_date, dtype: datetime64[us]

In [27]:
df_trans["kyc_status"].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [28]:
df_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  datetime64[us]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(9)
memory usage: 3.3 MB

In [29]:
df_trans.to_csv("../data/processed/clean_transactions.csv", index=False)

In [30]:
df_trans.shape

(32778, 13)

In [31]:
# Task 3: Clean Scheme performance Data

In [32]:
df_perf = pd.read_csv("../data/raw/07_scheme_performance.csv")

In [33]:
df_perf.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [34]:
df_perf.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [35]:
df_perf.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [36]:
df_perf.duplicated().sum()

np.int64(0)

In [37]:
df_perf.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [38]:
return_columns = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct",
    "benchmark_3yr_pct",
    "alpha",
    "beta",
    "sharpe_ratio",
    "sortino_ratio",
    "std_dev_ann_pct",
    "max_drawdown_pct"
]

df_perf[return_columns].dtypes

return_1yr_pct       float64
return_3yr_pct       float64
return_5yr_pct       float64
benchmark_3yr_pct    float64
alpha                float64
beta                 float64
sharpe_ratio         float64
sortino_ratio        float64
std_dev_ann_pct      float64
max_drawdown_pct     float64
dtype: object

In [39]:
(df_perf["sharpe_ratio"] < 0).sum()

np.int64(0)

In [40]:
df_perf["expense_ratio_pct"].describe()

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

In [41]:
(df_perf["expense_ratio_pct"] < 0.1).sum(), (df_perf["expense_ratio_pct"] > 2.5).sum()

(np.int64(0), np.int64(0))

In [42]:
df_perf.to_csv("../data/processed/clean_performance.csv", index=False)

In [43]:
import os

os.listdir("../data/raw/")

['01_fund_master.csv',
 '02_nav_history.csv',
 '03_aum_by_fund_house.csv',
 '04_monthly_sip_inflows.csv',
 '05_category_inflows.csv',
 '06_industry_folio_count.csv',
 '07_scheme_performance.csv',
 '08_investor_transactions.csv',
 '09_portfolio_holdings.csv',
 '10_benchmark_indices.csv',
 'axis_bluechip_nav.csv',
 'hdfc_top_100_nav.csv',
 'icici_bluechip_nav.csv',
 'kotak_bluechip_nav.csv',
 'nippon_large_cap_nav.csv',
 'sbi_bluechip_nav.csv']

In [44]:
# Task 4: Clean Fund Master Data

In [45]:
df_fund = pd.read_csv("../data/raw/01_fund_master.csv")
df_fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [46]:
df_fund.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [47]:
df_fund["launch_date"] = pd.to_datetime(df_fund["launch_date"])
df_fund["launch_date"].dtype

dtype('<M8[us]')

In [48]:
df_fund["amfi_code"].duplicated().sum()

np.int64(0)

In [49]:
df_fund["expense_ratio_pct"].describe()

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

In [50]:
(df_fund["expense_ratio_pct"] < 0.1).sum(), (df_fund["expense_ratio_pct"] > 2.5).sum()

(np.int64(0), np.int64(0))

In [51]:
(df_fund["exit_load_pct"] < 0).sum()

np.int64(0)

In [52]:
(df_fund["min_sip_amount"] <= 0).sum(), (df_fund["min_lumpsum_amount"] <= 0).sum()

(np.int64(0), np.int64(0))

In [53]:
df_fund.to_csv("../data/processed/clean_fund_master.csv", index=False)

In [54]:
# Task 5: Clean Aum by fund house Data

In [55]:
df_aum = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")
df_aum.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB

In [56]:
df_aum.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [57]:
df_aum.duplicated().sum()

np.int64(0)

In [58]:
df_aum["date"] = pd.to_datetime(df_aum["date"])
df_aum["date"].dtype

dtype('<M8[us]')

In [59]:
df_aum[["aum_lakh_crore", "aum_crore", "num_schemes"]].describe()

       aum_lakh_crore     aum_crore  num_schemes
count       90.000000  9.000000e+01    90.000000
mean         4.352889  4.352889e+05   152.200000
std          2.734328  2.734328e+05    52.108832
min          1.050000  1.050000e+05    56.000000
25%          2.525000  2.525000e+05    95.000000
50%          3.450000  3.450000e+05   172.500000
75%          5.675000  5.675000e+05   195.000000
max         12.500000  1.250000e+06   216.000000

In [60]:
(df_aum["aum_lakh_crore"] <= 0).sum(), (df_aum["aum_crore"] <= 0).sum(), (df_aum["num_schemes"] <= 0).sum()

(np.int64(0), np.int64(0), np.int64(0))

In [61]:
df_aum.to_csv("../data/processed/clean_aum_by_fund_house.csv", index=False)

In [62]:
# Task 6: Clean monthly sip inflows Data

In [63]:
df_sip = pd.read_csv("../data/raw/04_monthly_sip_inflows.csv")
df_sip.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), str(1)
memory usage: 2.4 KB

In [64]:
df_sip.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [65]:
df_sip.duplicated().sum()

np.int64(0)

In [66]:
df_sip["yoy_growth_pct"].isnull().sum()

np.int64(12)

In [67]:
df_sip[df_sip["yoy_growth_pct"].isnull()]

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN
5,2022-06,12276,5.60,7.50,5.18,NaN
6,2022-07,12140,5.65,9.21,5.25,NaN
7,2022-08,12694,5.71,8.90,5.31,NaN
8,2022-09,12976,5.80,9.40,5.41,NaN
9,2022-10,13040,5.93,9.52,5.55,NaN
10,2022-11,13306,6.00,8.80,5.62,NaN
11,2022-12,13573,6.05,7.60,5.70,NaN

In [68]:
df_sip["month"] = pd.to_datetime(df_sip["month"])
df_sip["month"].dtype

dtype('<M8[us]')

In [69]:
df_sip["month"].duplicated().sum()

np.int64(0)

In [70]:
(df_sip["sip_inflow_crore"] <= 0).sum(), \
(df_sip["active_sip_accounts_crore"] <= 0).sum(), \
(df_sip["new_sip_accounts_lakh"] <= 0).sum(), \
(df_sip["sip_aum_lakh_crore"] <= 0).sum()

(np.int64(0), np.int64(0), np.int64(0), np.int64(0))

In [71]:
df_sip["yoy_growth_pct"].describe()

count    36.000000
mean     31.456944
std      11.768190
min      15.800000
25%      20.245000
50%      28.295000
75%      40.807500
max      53.050000
Name: yoy_growth_pct, dtype: float64

In [72]:
df_sip.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     datetime64[us]
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: datetime64[us](1), float64(4), int64(1)
memory usage: 2.4 KB

In [73]:
df_sip.to_csv("../data/processed/clean_monthly_sip.csv", index=False)

In [74]:
# Task 7: Clean category inflows Data

In [75]:
df_category = pd.read_csv("../data/raw/05_category_inflows.csv")
df_category.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    str
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.5 KB

In [76]:
df_category.duplicated().sum()

np.int64(0)

In [77]:
df_category.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [78]:
df_category["month"] = pd.to_datetime(df_category["month"])
df_category["month"].dtype

dtype('<M8[us]')

In [79]:
df_category["category"].unique()

<StringArray>
[        'Large Cap',           'Mid Cap',         'Small Cap',
         'Flexi Cap',   'Large & Mid Cap',              'ELSS',
      'Value/Contra', 'Sectoral/Thematic',            'Liquid',
    'Short Duration',              'Gilt',            'Hybrid']
Length: 12, dtype: str

In [80]:
df_category["net_inflow_crore"].describe()

count      144.000000
mean      6473.881944
std       9718.335947
min        437.000000
25%       1801.250000
50%       4148.000000
75%       5304.000000
max      41952.000000
Name: net_inflow_crore, dtype: float64

In [81]:
df_category.duplicated(subset=["month", "category"]).sum()

np.int64(0)

In [82]:
df_category.to_csv("../data/processed/clean_category.csv", index=False)

In [83]:
# Task 8: Clean industry foli count Data

In [84]:
df_folio = pd.read_csv("../data/raw/06_industry_folio_count.csv")
df_folio.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     str
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), str(1)
memory usage: 1.1 KB

In [85]:
df_folio.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [86]:
df_folio.duplicated().sum()

np.int64(0)

In [87]:
df_folio["month"] = pd.to_datetime(df_folio["month"])
df_folio["month"].dtype

dtype('<M8[us]')

In [88]:
(
    (df_folio["total_folios_crore"] < 0).sum(),
    (df_folio["equity_folios_crore"] < 0).sum(),
    (df_folio["debt_folios_crore"] < 0).sum(),
    (df_folio["hybrid_folios_crore"] < 0).sum(),
    (df_folio["others_folios_crore"] < 0).sum()
)

(np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0))

In [89]:
df_folio.to_csv("../data/processed/clean_industry_folio_count.csv", index=False)

In [90]:
# Task 9: Clean portfolio holdings Data

In [91]:
df_holdings = pd.read_csv("../data/raw/09_portfolio_holdings.csv")
df_holdings.info()

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    str
dtypes: float64(3), int64(1), str(4)
memory usage: 20.3 KB

In [92]:
df_holdings.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [93]:
df_holdings.duplicated().sum()

np.int64(0)

In [94]:
df_holdings.columns

Index(['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct',
       'market_value_cr', 'current_price_inr', 'portfolio_date'],
      dtype='str')

In [95]:
df_holdings["portfolio_date"] = pd.to_datetime(df_holdings["portfolio_date"])
df_holdings["portfolio_date"].dtype

dtype('<M8[us]')

In [96]:
(df_holdings["weight_pct"] < 0).sum(), \
(df_holdings["weight_pct"] > 100).sum()

(np.int64(0), np.int64(0))

In [97]:
(df_holdings["market_value_cr"] <= 0).sum(), \
(df_holdings["current_price_inr"] <= 0).sum()

(np.int64(0), np.int64(0))

In [98]:
df_holdings.duplicated(
    subset=["amfi_code", "stock_symbol", "portfolio_date"]
).sum()

np.int64(0)

In [99]:
df_holdings.to_csv("../data/processed/clean_portfolio.csv", index=False)

In [100]:
# Task 10: Clean portfolio holdings Data

In [101]:
df_benchmark = pd.read_csv("../data/raw/10_benchmark_indices.csv")
df_benchmark.info()

<class 'pandas.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   str
 1   index_name   8050 non-null   str
 2   close_value  8050 non-null   float64
dtypes: float64(1), str(2)
memory usage: 188.8 KB

In [102]:
df_benchmark.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [103]:
df_benchmark.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [104]:
df_benchmark.duplicated().sum()

np.int64(0)

In [105]:
df_benchmark.duplicated(subset=["date", "index_name"]).sum()

np.int64(0)

In [106]:
df_benchmark["date"] = pd.to_datetime(df_benchmark["date"])
df_benchmark["date"].dtype

dtype('<M8[us]')

In [107]:
(df_benchmark["close_value"] <= 0).sum()

np.int64(0)

In [108]:
df_benchmark["index_name"].unique()

<StringArray>
[        'NIFTY50',        'NIFTY100', 'NIFTY_MIDCAP150',    'BSE_SMALLCAP',
        'NIFTY500',   'CRISIL_LIQUID',     'CRISIL_GILT']
Length: 7, dtype: str

In [109]:
df_benchmark["index_name"].value_counts()

index_name
NIFTY50            1150
NIFTY100           1150
NIFTY_MIDCAP150    1150
BSE_SMALLCAP       1150
NIFTY500           1150
CRISIL_LIQUID      1150
CRISIL_GILT        1150
Name: count, dtype: int64

In [110]:
df_benchmark.to_csv("../data/processed/clean_benchmark.csv", index=False)

In [111]:
#creating and Connecting to  database

In [112]:
%pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\shami\appdata\local\programs\python\python312\lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\shami\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shami\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.11.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [113]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///../data/db/bluestock_mf.db")

print("Connected to SQLite database!")

Connected to SQLite database!

In [114]:
import pandas as pd

df_fund = pd.read_csv(
    "../data/processed/clean_fund_master.csv"
)

df_fund.to_sql(
    "dim_fund",
    engine,
    if_exists="append",
    index=False
)

print("dim_fund loaded:", len(df_fund))

dim_fund loaded: 40

In [115]:
df_nav = pd.read_csv(
    "../data/processed/clean_nav.csv"
)

df_nav["date"] = pd.to_datetime(df_nav["date"])

dates = df_nav["date"].drop_duplicates().sort_values()

df_date = pd.DataFrame({
    "full_date": dates
})

df_date["date_key"] = range(1, len(df_date) + 1)
df_date["year"] = df_date["full_date"].dt.year
df_date["quarter"] = df_date["full_date"].dt.quarter
df_date["month"] = df_date["full_date"].dt.month
df_date["month_name"] = df_date["full_date"].dt.month_name()
df_date["day"] = df_date["full_date"].dt.day
df_date["day_name"] = df_date["full_date"].dt.day_name()

df_date.to_sql(
    "dim_date",
    engine,
    if_exists="append",
    index=False
)

print("dim_date loaded:", len(df_date))

dim_date loaded: 1150

In [116]:
df_nav = pd.read_csv(
    "../data/processed/clean_nav.csv"
)

df_nav["date"] = pd.to_datetime(df_nav["date"])

df_nav = df_nav.sort_values(
    ["amfi_code", "date"]
)

df_nav["daily_return"] = (
    df_nav.groupby("amfi_code")["nav"].pct_change()
)

In [117]:
df_date_db = pd.read_sql(
    "SELECT date_key, full_date FROM dim_date",
    engine
)

df_date_db["full_date"] = pd.to_datetime(
    df_date_db["full_date"]
)

df_nav = df_nav.merge(
    df_date_db,
    left_on="date",
    right_on="full_date",
    how="left"
)

In [118]:
df_nav_fact = df_nav[
    [
        "amfi_code",
        "date_key",
        "date",
        "nav",
        "daily_return"
    ]
].copy()

df_nav_fact = df_nav_fact.rename(
    columns={"date": "nav_date"}
)

df_nav_fact["amfi_code"] = (
    df_nav_fact["amfi_code"].astype(str)
)

df_nav_fact.to_sql(
    "fact_nav",
    engine,
    if_exists="append",
    index=False
)

print("fact_nav loaded:", len(df_nav_fact))

fact_nav loaded: 92000

In [119]:
df_trans = pd.read_csv(
    "../data/processed/clean_transactions.csv"
)

df_trans["transaction_date"] = pd.to_datetime(
    df_trans["transaction_date"]
)

In [120]:
df_date_db = pd.read_sql(
    "SELECT date_key, full_date FROM dim_date",
    engine
)

df_date_db["full_date"] = pd.to_datetime(
    df_date_db["full_date"]
)

df_trans = df_trans.merge(
    df_date_db,
    left_on="transaction_date",
    right_on="full_date",
    how="left"
)

print(
    "Missing date keys:",
    df_trans["date_key"].isna().sum()
)

Missing date keys: 0

In [121]:
df_trans_fact = df_trans[
    [
        "investor_id",
        "amfi_code",
        "date_key",
        "transaction_date",
        "transaction_type",
        "amount_inr",
        "state",
        "city",
        "city_tier",
        "age_group",
        "gender",
        "annual_income_lakh",
        "payment_mode",
        "kyc_status"
    ]
].copy()

df_trans_fact["amfi_code"] = (
    df_trans_fact["amfi_code"].astype(str)
)

In [122]:
df_trans_fact.to_sql(
    "fact_transactions",
    engine,
    if_exists="append",
    index=False
)

print(
    "fact_transactions loaded:",
    len(df_trans_fact)
)

fact_transactions loaded: 56325

In [123]:
df_perf = pd.read_csv(
    "../data/processed/clean_performance.csv"
)

df_perf_fact = df_perf[
    [
        "amfi_code",
        "scheme_name",
        "fund_house",
        "category",
        "plan",
        "return_1yr_pct",
        "return_3yr_pct",
        "return_5yr_pct",
        "benchmark_3yr_pct",
        "alpha",
        "beta",
        "sharpe_ratio",
        "sortino_ratio",
        "std_dev_ann_pct",
        "max_drawdown_pct",
        "aum_crore",
        "expense_ratio_pct",
        "morningstar_rating",
        "risk_grade"
    ]
].copy()

df_perf_fact["amfi_code"] = (
    df_perf_fact["amfi_code"].astype(str)
)

df_perf_fact.to_sql(
    "fact_performance",
    engine,
    if_exists="append",
    index=False
)

print(
    "fact_performance loaded:",
    len(df_perf_fact)
)

fact_performance loaded: 40

In [124]:
df_aum = pd.read_csv(
    "../data/processed/clean_aum_by_fund_house.csv"
)

df_aum["date"] = pd.to_datetime(
    df_aum["date"]
)

In [125]:
df_date_db = pd.read_sql(
    "SELECT date_key, full_date FROM dim_date",
    engine
)

df_date_db["full_date"] = pd.to_datetime(
    df_date_db["full_date"]
)

df_aum = df_aum.merge(
    df_date_db,
    left_on="date",
    right_on="full_date",
    how="left"
)

print(
    "Missing date keys:",
    df_aum["date_key"].isna().sum()
)

Missing date keys: 0

In [126]:
df_aum_fact = df_aum[
    [
        "date_key",
        "date",
        "fund_house",
        "aum_lakh_crore",
        "aum_crore",
        "num_schemes"
    ]
].copy()

df_aum_fact = df_aum_fact.rename(
    columns={"date": "aum_date"}
)

In [127]:
df_aum_fact.to_sql(
    "fact_aum",
    engine,
    if_exists="append",
    index=False
)

print(
    "fact_aum loaded:",
    len(df_aum_fact)
)

fact_aum loaded: 160

In [128]:
tables = pd.read_sql(
    """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table';
    """,
    engine
)

tables

                    name
0               dim_fund
1               dim_date
2               fact_nav
3      fact_transactions
4       fact_performance
5               fact_aum
6    monthly_sip_inflows
7       category_inflows
8   industry_folio_count
9     portfolio_holdings
10     benchmark_indices

In [129]:
table_names = [
    "dim_fund",
    "dim_date",
    "fact_nav",
    "fact_transactions",
    "fact_performance",
    "fact_aum"
]

for table in table_names:
    count = pd.read_sql(
        f"SELECT COUNT(*) AS count FROM {table}",
        engine
    ).iloc[0]["count"]

    print(f"{table}: {count}")

dim_fund: 120
dim_date: 2447
fact_nav: 138000
fact_transactions: 89103
fact_performance: 80
fact_aum: 250

In [130]:
print(
    "Transaction dates missing:",
    df_trans["transaction_date"].isin(
        pd.to_datetime(df_date["full_date"])
    ).eq(False).sum()
)

print(
    "AUM dates missing:",
    df_aum["date"].isin(
        pd.to_datetime(df_date["full_date"])
    ).eq(False).sum()
)

Transaction dates missing: 9231
AUM dates missing: 20

In [131]:
# Get dates from transactions
transaction_dates = df_trans["transaction_date"].dropna()

# Get dates from AUM
aum_dates = df_aum["date"].dropna()

# Combine all dates
all_dates = pd.concat(
    [df_nav["date"], transaction_dates, aum_dates]
).drop_duplicates().sort_values()

print("Total unique dates needed:", len(all_dates))

Total unique dates needed: 1297

In [132]:
existing_dates = pd.read_sql(
    "SELECT full_date FROM dim_date",
    engine
)

existing_dates["full_date"] = pd.to_datetime(
    existing_dates["full_date"]
)

missing_dates = all_dates[
    ~all_dates.isin(existing_dates["full_date"])
].sort_values()

print("New dates to add:", len(missing_dates))

New dates to add: 0

In [133]:
new_dates = pd.DataFrame({
    "full_date": missing_dates
})

max_key = pd.read_sql(
    "SELECT MAX(date_key) AS max_key FROM dim_date",
    engine
).iloc[0]["max_key"]

new_dates["date_key"] = range(
    int(max_key) + 1,
    int(max_key) + 1 + len(new_dates)
)

new_dates["year"] = new_dates["full_date"].dt.year
new_dates["quarter"] = new_dates["full_date"].dt.quarter
new_dates["month"] = new_dates["full_date"].dt.month
new_dates["month_name"] = new_dates["full_date"].dt.month_name()
new_dates["day"] = new_dates["full_date"].dt.day
new_dates["day_name"] = new_dates["full_date"].dt.day_name()

In [134]:
new_dates.to_sql(
    "dim_date",
    engine,
    if_exists="append",
    index=False
)

print("dim_date updated successfully!")

dim_date updated successfully!

In [135]:
count = pd.read_sql(
    "SELECT COUNT(*) AS count FROM dim_date",
    engine
).iloc[0]["count"]

print("dim_date rows:", count)

dim_date rows: 2447

In [136]:
df_sip = pd.read_csv(
    "../data/processed/clean_monthly_sip.csv"
)

df_sip["month"] = pd.to_datetime(df_sip["month"])

df_sip.to_sql(
    "monthly_sip_inflows",
    engine,
    if_exists="replace",
    index=False
)

print("monthly_sip_inflows loaded:", len(df_sip))

monthly_sip_inflows loaded: 48

In [137]:
df_category = pd.read_csv(
    "../data/processed/clean_category.csv"
)

df_category["month"] = pd.to_datetime(
    df_category["month"]
)

df_category.to_sql(
    "category_inflows",
    engine,
    if_exists="replace",
    index=False
)

print("category_inflows loaded:", len(df_category))

category_inflows loaded: 144

In [138]:
df_folio = pd.read_csv(
    "../data/processed/clean_industry_folio_count.csv"
)

df_folio["month"] = pd.to_datetime(
    df_folio["month"]
)

df_folio.to_sql(
    "industry_folio_count",
    engine,
    if_exists="replace",
    index=False
)

print("industry_folio_count loaded:", len(df_folio))

industry_folio_count loaded: 21

In [139]:
df_holdings = pd.read_csv(
    "../data/processed/clean_portfolio.csv"
)

df_holdings["portfolio_date"] = pd.to_datetime(
    df_holdings["portfolio_date"]
)

df_holdings.to_sql(
    "portfolio_holdings",
    engine,
    if_exists="replace",
    index=False
)

print("portfolio_holdings loaded:", len(df_holdings))

portfolio_holdings loaded: 322

In [140]:
df_benchmark = pd.read_csv(
    "../data/processed/clean_benchmark.csv"
)

df_benchmark["date"] = pd.to_datetime(
    df_benchmark["date"]
)

df_benchmark.to_sql(
    "benchmark_indices",
    engine,
    if_exists="replace",
    index=False
)

print("benchmark_indices loaded:", len(df_benchmark))

benchmark_indices loaded: 8050

In [141]:
new_tables = [
    "monthly_sip_inflows",
    "category_inflows",
    "industry_folio_count",
    "portfolio_holdings",
    "benchmark_indices"
]

for table in new_tables:
    count = pd.read_sql(
        f"SELECT COUNT(*) AS count FROM {table}",
        engine
    ).iloc[0]["count"]

    print(f"{table}: {count}")

monthly_sip_inflows: 48
category_inflows: 144
industry_folio_count: 21
portfolio_holdings: 322
benchmark_indices: 8050

In [142]:
query1 = """
SELECT
    amfi_code,
    scheme_name,
    aum_crore
FROM fact_performance
ORDER BY aum_crore DESC
LIMIT 5;
"""

result1 = pd.read_sql(query1, engine)
result1

  amfi_code                                        scheme_name  aum_crore
0    148568  Mirae Asset Emerging Bluechip Fund - Regular -...      49046
1    148568  Mirae Asset Emerging Bluechip Fund - Regular -...      49046
2    120842      Kotak Emerging Equity Fund - Regular - Growth      47469
3    120842      Kotak Emerging Equity Fund - Regular - Growth      47469
4    118634     Nippon India Small Cap Fund - Regular - Growth      43630

In [143]:
query2 = """
SELECT
    strftime('%Y-%m', nav_date) AS month,
    ROUND(AVG(nav), 2) AS average_nav
FROM fact_nav
GROUP BY strftime('%Y-%m', nav_date)
ORDER BY month;
"""

result2 = pd.read_sql(query2, engine)
result2

      month  average_nav
0   2022-01       207.06
1   2022-02       207.72
2   2022-03       209.69
3   2022-04       211.83
4   2022-05       212.73
5   2022-06       213.86
6   2022-07       213.96
7   2022-08       215.68
8   2022-09       218.49
9   2022-10       219.53
10  2022-11       223.47
11  2022-12       226.76
12  2023-01       230.67
13  2023-02       233.85
14  2023-03       238.01
15  2023-04       240.61
16  2023-05       241.89
17  2023-06       244.61
18  2023-07       245.78
19  2023-08       247.73
20  2023-09       251.83
21  2023-10       255.61
22  2023-11       258.35
23  2023-12       262.02
24  2024-01       264.62
25  2024-02       266.33
26  2024-03       269.60
27  2024-04       271.30
28  2024-05       273.45
29  2024-06       275.47
30  2024-07       279.02
31  2024-08       279.74
32  2024-09       281.02
33  2024-10       282.13
34  2024-11       285.24
35  2024-12       285.27
36  2025-01       288.04
37  2025-02       291.74
38  2025-03       296.16
39  2025-04       299.41
40  2025-05       303.94
41  2025-06       306.88
42  2025-07       309.73
43  2025-08       313.18
44  2025-09       316.13
45  2025-10       321.45
46  2025-11       325.68
47  2025-12       331.73
48  2026-01       337.12
49  2026-02       342.08
50  2026-03       347.19
51  2026-04       355.03
52  2026-05       357.04

In [144]:
query3 = """
WITH yearly_sip AS (
    SELECT
        strftime('%Y', month) AS year,
        SUM(sip_inflow_crore) AS total_sip_inflow
    FROM monthly_sip_inflows
    GROUP BY strftime('%Y', month)
)

SELECT
    year,
    ROUND(total_sip_inflow, 2) AS total_sip_inflow,
    ROUND(
        (total_sip_inflow - LAG(total_sip_inflow) OVER (ORDER BY year))
        * 100.0
        / LAG(total_sip_inflow) OVER (ORDER BY year),
        2
    ) AS yoy_growth_pct
FROM yearly_sip
ORDER BY year;
"""

result3 = pd.read_sql(query3, engine)
result3

   year  total_sip_inflow  yoy_growth_pct
0  2022          149437.0             NaN
1  2023          184763.0           23.64
2  2024          269781.0           46.01
3  2025          335740.0           24.45

In [145]:
query4 = """
SELECT
    state,
    COUNT(*) AS transaction_count,
    ROUND(SUM(amount_inr), 2) AS total_amount
FROM fact_transactions
GROUP BY state
ORDER BY transaction_count DESC;
"""

result4 = pd.read_sql(query4, engine)
result4

             state  transaction_count  total_amount
0           Punjab               8075   863605472.0
1   Madhya Pradesh               7958   840668132.0
2       Tamil Nadu               7607   853118494.0
3          Gujarat               7568   813861014.0
4          Haryana               7473   761531797.0
5      West Bengal               7452   808183863.0
6        Telangana               7390   794171641.0
7    Uttar Pradesh               7307   769984695.0
8            Delhi               7252   781228707.0
9        Karnataka               7161   744861362.0
10       Rajasthan               6966   807015898.0
11     Maharashtra               6894   739481786.0

In [146]:
query5 = """
SELECT
    amfi_code,
    scheme_name,
    expense_ratio_pct
FROM dim_fund
WHERE expense_ratio_pct < 1
ORDER BY expense_ratio_pct;
"""

result5 = pd.read_sql(query5, engine)
result5

,amfi_code,scheme_name,expense_ratio_pct
0,118636,Nippon India Gilt Securities Fund - Regular - ...,0.55
1,118636,Nippon India Gilt Securities Fund - Regular - ...,0.55
2,118636,Nippon India Gilt Securities Fund - Regular - ...,0.55
3,100025,HDFC Short Term Debt Fund - Regular - Growth,0.56
4,100025,HDFC Short Term Debt Fund - Regular - Growth,0.56
5,100025,HDFC Short Term Debt Fund - Regular - Growth,0.56
6,120844,Kotak Liquid Fund - Regular - Growth,0.60
7,120844,Kotak Liquid Fund - Regular - Growth,0.60
8,120844,Kotak Liquid Fund - Regular - Growth,0.60
9,119552,SBI Bluechip Fund - Direct Plan - Growth,0.66
10,119552,SBI Bluechip Fund - Direct Plan - Growth,0.66
11,119552,SBI Bluechip Fund - Direct Plan - Growth,0.66
12,119599,SBI Small Cap Fund - Direct Plan - Growth,0.72
13,118633,Nippon India Large Cap Fund - Direct - Growth,0.72
14,119599,SBI Small Cap Fund - Direct Plan - Growth,0.72
15,118633,Nippon India Large Cap Fund - Direct - Growth,0.72
16,119599,SBI Small Cap Fund - Direct Plan - Growth,0.72
17,118633,Nippon India Large Cap Fund - Direct - Growth,0.72
18,120507,ICICI Pru Liquid Fund - Regular - Growth,0.74
19,120507,ICICI Pru Liquid Fund - Regular - Growth,0.74
20,120507,ICICI Pru Liquid Fund - Regular - Growth,0.74
21,119093,Axis Bluechip Fund - Direct - Growth,0.75
22,119093,Axis Bluechip Fund - Direct - Growth,0.75
23,119093,Axis Bluechip Fund - Direct - Growth,0.75
24,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,0.77
25,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,0.77
26,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,0.77
27,125498,HDFC Mid-Cap Opportunities Fund - Direct - Growth,0.78
28,125498,HDFC Mid-Cap Opportunities Fund - Direct - Growth,0.78
29,125498,HDFC Mid-Cap Opportunities Fund - Direct - Growth,0.78
30,101208,ABSL Liquid Fund - Regular - Growth,0.79
31,101208,ABSL Liquid Fund - Regular - Growth,0.79
32,101208,ABSL Liquid Fund - Regular - Growth,0.79
33,120504,ICICI Pru Bluechip Fund - Direct - Growth,0.80
34,120504,ICICI Pru Bluechip Fund - Direct - Growth,0.80
35,120504,ICICI Pru Bluechip Fund - Direct - Growth,0.80
36,118635,Nippon India ETF Nifty 50 BeES,0.89
37,118635,Nippon India ETF Nifty 50 BeES,0.89
38,118635,Nippon India ETF Nifty 50 BeES,0.89
39,125497,HDFC Top 100 Fund - Direct Plan - Growth,0.92
40,125497,HDFC Top 100 Fund - Direct Plan - Growth,0.92
41,125497,HDFC Top 100 Fund - Direct Plan - Growth,0.92

In [147]:
query6 = """
SELECT
    transaction_type,
    COUNT(*) AS transaction_count,
    ROUND(AVG(amount_inr), 2) AS average_amount
FROM fact_transactions
GROUP BY transaction_type
ORDER BY average_amount DESC;
"""

result6 = pd.read_sql(query6, engine)
result6

  transaction_type  transaction_count  average_amount
0          Lumpsum              22025       254766.23
1       Redemption              13477       250555.72
2              SIP              53601        11002.54

In [148]:
query7 = """
SELECT
    amfi_code,
    ROUND(AVG(nav), 2) AS average_nav
FROM fact_nav
GROUP BY amfi_code
ORDER BY average_nav DESC
LIMIT 10;
"""

result7 = pd.read_sql(query7, engine)
result7

  amfi_code  average_nav
0    120844      3705.88
1    125497       797.45
2    100016       566.19
3    149322       439.18
4    101206       435.98
5    101208       358.39
6    120841       355.08
7    120507       334.08
8    120505       284.00
9    120506       274.32

In [149]:
query8 = """
SELECT
    risk_category,
    COUNT(*) AS fund_count
FROM dim_fund
GROUP BY risk_category
ORDER BY fund_count DESC;
"""

result8 = pd.read_sql(query8, engine)
result8

     risk_category  fund_count
0         Moderate          48
1             High          24
2        Very High          18
3              Low          18
4  Moderately High          12

In [150]:
query9 = """
SELECT
    city_tier,
    COUNT(*) AS transaction_count,
    ROUND(SUM(amount_inr), 2) AS total_amount
FROM fact_transactions
GROUP BY city_tier
ORDER BY total_amount DESC;
"""

result9 = pd.read_sql(query9, engine)
result9

  city_tier  transaction_count  total_amount
0       T30              59024  6.316576e+09
1       B30              30079  3.261137e+09

In [151]:
query10 = """
SELECT
    fund_house,
    ROUND(SUM(aum_crore), 2) AS total_aum_crore
FROM fact_aum
GROUP BY fund_house
ORDER BY total_aum_crore DESC;
"""

result10 = pd.read_sql(query10, engine)
result10

                 fund_house  total_aum_crore
0           SBI Mutual Fund       23628000.0
1       ICICI Prudential MF       17609000.0
2          HDFC Mutual Fund       16016000.0
3           Nippon India MF       10957000.0
4         Kotak Mahindra MF        9801000.0
5  Aditya Birla Sun Life MF        8583000.0
6           UTI Mutual Fund        7488000.0
7          Axis Mutual Fund        7023000.0
8            Mirae Asset MF        4366000.0
9           DSP Mutual Fund        3940000.0